name: e_waste_management_system
description: A simple e-waste management system mobile app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

include: package:flutter_lints/flutter.yaml

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+8
  intl: ^0.19.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
